### ISSUE TITLE
Add (optional) UUID to log name

### ISSUE THREAD

**Issue by josephlewis42** [logstash-plugins/logstash-output-google_cloud_storage#23]
This proposal is to add the ability for the user to request a UUID in the log name and optionally turn off the hostname e.g. `logstash_2018-01-01T01:01:00.part1.{{UUID}}.log`. This has the following benefits:

1. A new log won't clobber the old one after Logstash is restarted on a host with the same name. See  @neuromantik33 description in #20 for more info.
2. Users could turn off using the hostname in their file names if:
  * They don't want an information leak: @joshdvir opened #9 for this
  * They needed to be able to use a single glob to match their logs to import into BigQuery @arslanm had to modify the plugin in #19 to do this

Thoughts @neuromantik33, @joshdvir and @arslanm?

**Comment by joshdvir** [comment]
LGTM

**Comment by josephlewis42** [comment]
I have this functionality built out now, it would be awesome if one of ya'll would give it a go and give thumbs up/down. I have a pre-release gem published [here](https://github.com/josephlewis42/personal_codebase/releases/download/logstash-release/logstash-output-google_cloud_storage-3.1.0.gem), the version is 3.1.0.

There are two new configuration options. Both are boolean:

 * `include_uuid` - default false, appends a UUID before the file extension `.log[.gz]`
 * `include_hostname` - default true, whether or not to include the hostname in the prefix.
