### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by shaharmor** [logstash-plugins/logstash-output-google_cloud_storage#4]
Hi,

It seems that the plugin doesn't work.
debugging shows that everything is OK, but the upload doesn't succeed (No error).
https://github.com/logstash-plugins/logstash-output-google_cloud_storage/blob/master/lib/logstash/outputs/google_cloud_storage.rb#L387
this line shows nil for both params

**Comment by shaharmor** [comment]
It seems that the version in logstash plugins repository is different then this one

**Comment by electrical** [comment]
Hi,

do you mean that the released version that is installable doesn't work and is different from what is in the master branch here?
If so, i see that the latest change was to move the API from the beta version to the released v1 API at https://github.com/logstash-plugins/logstash-output-google_cloud_storage/pull/1
We should be doing a release soon for this plugin so it will work.

**Comment by shaharmor** [comment]
Yes, i debugged the issue to be that the version listen in the installable version is v1beta1, which stops the plugin from working.
When i updated the file to v1 it started working.

**Comment by electrical** [comment]
Thank you for confirming @shaharmor I'll make sure we do a release today.

**Comment by purbon** [comment]
New version has been release, https://rubygems.org/gems/logstash-output-google_cloud_storage

/cheers
